Wow\WowBundle\Entity\Articles:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    title:
      type: string
      length: '255'
    date:
      type: date
      length: null
    shortdesc:
      type: string
      length: '255'
    description:
      type: text
      length: null
    author:
      type: string
      length: '255'
  lifecycleCallbacks: {  }
