WowWowBundle_homepage:
    pattern:  /
    defaults: { _controller: WowWowBundle:Default:index }

WowWowBundle_newspage:
    pattern:  /news
    defaults: { _controller: WowWowBundle:News:index }

WowWowBundle_articlespage:
    pattern:  /articles
    defaults: { _controller: WowWowBundle:Articles:index }

show_articlespage:
    pattern:  /articles/show/{id}
    defaults: { _controller: WowWowBundle:Articles:show }

startpage:
    pattern:  /start
    defaults: { _controller: WowWowBundle:Start:index }

cabinetpage:
    pattern:  /cabinet
    defaults: { _controller: WowWowBundle:Cabinet:index }

changespage:
    pattern:  /changes
    defaults: { _controller: WowWowBundle:Changes:index }

registrationpage:
    pattern:  /registration
    defaults: { _controller: WowWowBundle:Registration:index }


