Wow\WowBundle\Entity\Registration:
    properties:
        login:
            - NotBlank: ~
        pwd:
            - NotBlank: ~
            - MinLength:  7
        pwd2:
            - NotBlank: ~
            - MinLength: 7
          
        email:
            - NotBlank: ~
            - Email: ~
    getters:
        passwordLegal:
            - "True": { message: "The password cannot match your first name" }